# Doctrine MongoDB support
doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_server%"
    default_database: "%mongodb_database%"
    document_managers:
        default:
            auto_mapping: true

pim_catalog:
    storage_driver: 'doctrine/mongodb-odm'
